export default {
  specialLabels: {
    "padding\\[0\\]": "上",
    "padding\\[1\\]": "右",
    "padding\\[2\\]": "下",
    "padding\\[3\\]": "左",
    "borderRadius\\[0\\]": "上",
    "borderRadius\\[1\\]": "右",
    "borderRadius\\[2\\]": "下",
    "borderRadius\\[3\\]": "左",
    "axisLine.symbol.*\\[0\\]": "起始",
    "axisLine.symbol.*\\[1\\]": "终止",
    "colorStops\\[0\\]$": "起始",
    "colorStops\\[1\\]$": "终止",
    "reg.order": "多项式回归最高次数",
  },
  special: {
    "axis.type": {
      type: "select",
      options: [
        { label: "类目轴", value: "category" },
        { label: "数值轴", value: "value" },
      ],
    },
    "lineStyle.type": {
      type: "select",
      options: [
        { label: "实线", value: "solid" },
        { label: "----", value: "dashed" },
        { label: ".....", value: "dotted" },
      ],
    },
    "backgroundPalette.mode": {
      type: "select",
      options: [
        { label: "纯色", value: "pureColor" },
        { label: "线性渐变", value: "linear" },
        { label: "径向渐变", value: "radial" },
      ],
    },
    "palette.mode": {
      type: "select",
      options: [
        { label: "纯色", value: "pureColor" },
        { label: "线性渐变", value: "linear" },
      ],
    },
    "backgroundStyle.mode": {
      type: "select",
      options: [
        { label: "纯色", value: "pureColor" },
        { label: "线性渐变", value: "linear" },
      ],
    },
    "label.position": {
      type: "select",
      options: [
        { label: "上", value: "top" },
        { label: "下", value: "bottom" },
        { label: "左", value: "left" },
        { label: "右", value: "right" },
        { label: "inside", value: "inside" },
        { label: "insideLeft", value: "insideLeft" },
        { label: "insideRight", value: "insideRight" },
        { label: "insideTop", value: "insideTop" },
        { label: "insideBottom", value: "insideBottom" },
        { label: "insideTopLeft", value: "insideTopLeft" },
        { label: "insideBottomLeft", value: "insideBottomLeft" },
        { label: "insideTopRight", value: "insideTopRight" },
        { label: "insideBottomRight", value: "insideBottomRight" },
      ],
    },
    "xAxis.position": {
      type: "select",
      options: [
        { label: "上", value: "top" },
        { label: "下", value: "bottom" },
        { label: "左", value: "left" },
        { label: "右", value: "right" },
      ],
    },
    "yAxis.position": {
      type: "select",
      options: [
        { label: "上", value: "top" },
        { label: "下", value: "bottom" },
        { label: "左", value: "left" },
        { label: "右", value: "right" },
      ],
    },
    "Axis.type": {
      type: "select",
      options: [
        { label: "类目轴", value: "category" },
        { label: "数值轴", value: "value" },
      ],
    },
    "axisLine.symbol\\[.\\]": {
      type: "select",
      options: [
        { label: "无", value: "none" },
        { label: "箭头", value: "arrow" },
      ],
    },
    mapObj: {
      type: "mapjson",
    },
    "reg.method": {
      type: "select",
      options: [
        { label: "线性回归", value: "linear" },
        { label: "指数回归", value: "exponential" },
        { label: "对数回归", value: "logarithmic" },
        { label: "多项式回归", value: "polynomial" },
      ],
    },
    "reg.formulaOn": {
      type: "select",
      options: [
        { label: "起始", value: "start" },
        { label: "末尾", value: "end" },
      ],
    },
  },
  selectOptions: {
    fontFamily: [
      { label: "serif", value: "serif" },
      { label: "monospace", value: "monospace" },
      { label: "Courier New", value: "Courier New" },
      { label: "微软雅黑", value: "Microsoft YaHei" },
    ],
    fontWeight: [
      { label: "普通", value: "normal" },
      { label: "粗体", value: "bold" },
      { label: "纤细", value: "lighter" },
    ],
    fontStyle: [
      { label: "普通", value: "normal" },
      { label: "斜体", value: "italic" },
    ],
    nameLocation: [
      { label: "起始", value: "start" },
      { label: "中间", value: "center" },
      { label: "末端", value: "end" },
    ],
    borderType: [
      { label: "实线", value: "solid" },
      { label: "----", value: "dashed" },
      { label: ".....", value: "dotted" },
    ],
    align: [
      { label: "靠左", value: "left" },
      { label: "居中", value: "center" },
      { label: "靠右", value: "right" },
    ],
    verticalAlign: [
      { label: "靠上", value: "top" },
      { label: "居中", value: "middle" },
      { label: "靠下", value: "bottom" },
    ],
    target: [
      { label: "空白页", value: "blank" },
      { label: "当前页", value: "self" },
    ],
    orient: [
      { label: "垂直", value: "vertical" },
      { label: "水平", value: "horizontal" },
    ],
    sort: [
      { label: "升序", value: "ascending" },
      { label: "降序", value: "decending" },
      { label: "默认", value: "none" },
    ],
    funnelAlign: [
      { label: "居中", value: "center" },
      { label: "上", value: "top" },
      { label: "下", value: "bottom" },
      { label: "左", value: "left" },
      { label: "右", value: "right" },
    ],
    shape: [
      { label: "多边形", value: "polygon" },
      { label: "圆", value: "circle" },
    ],
    symbol: [
      { label: "圆", value: "circle" },
      { label: "矩形", value: "rect" },
      { label: "圆角矩形", value: "roundRect" },
      { label: "三角形", value: "triangle" },
      { label: "菱形", value: "diamond" },
      { label: "pin", value: "pin" },
      { label: "箭头", value: "arrow" },
      { label: "无", value: "none" },
    ],
  },
  labels: {
    title: "标题",
    legend: "图例",
    color: "颜色",
    borderColor: "边框颜色",
    borderWidth: "边框宽度",
    borderRadius: "圆角半径",
    shadowBlur: "阴影模糊",
    shadowColor: "阴影颜色",
    shadowOffsetX: "阴影水平偏移",
    shadowOffsetY: "阴影垂直偏移",
    textBorderColor: "文本边框颜色",
    textBorderWidth: "文本边框宽度",
    textShadowColor: "文本阴影颜色",
    textShadowBlur: "文本阴影模糊",
    textShadowOffsetX: "文本阴影水平偏移",
    textShadowOffsetY: "文本阴影垂直偏移",
    backgroundColor: "背景色",
    label: "标签",
    grid: "网格",
    show: "显示",
    text: "文本",
    subtext: "副标题",
    textStyle: "文本样式",
    textAlign: "水平对齐",
    textVerticalAlign: "垂直对齐",
    align: "水平对齐",
    verticalAlign: "垂直对齐",
    link: "链接",
    target: "目标",
    sublink: "副标题链接",
    subtarget: "副标题目标",
    padding: "内边距",
    left: "距左侧",
    right: "距右侧",
    top: "距顶部",
    bottom: "距底部",
    itemGap: "间距",
    fontFamily: "字体",
    fontStyle: "字体样式",
    fontWeight: "字体粗细",
    fontSize: "字号",
    lineHeight: "行高",
    subtextStyle: "副标题样式",
    containLabel: "包含标签",
    paletteMode: "模式",
    pureColor: "纯色",
    linear: "线性渐变",
    type: "类型",
    name: "轴名",
    nameLocation: "轴名位置",
    position: "位置",
    nameGap: "间距",
    nameRotate: "旋转角度",
    inverse: "反向",
    nameTextStyle: "轴名样式",
    axisLine: "坐标轴线",
    axisTick: "刻度",
    axisLabel: "刻度标签",
    splitLine: "分隔线",
    interval: "间隔",
    symbol: "标志",
    symbolSize: "标志尺寸",
    symbolOffset: "标志偏移",
    lineStyle: "线条样式",
    width: "宽度",
    rotate: "旋转角度",
    inside: "朝内",
    length: "长度",
    borderRaduis: "边框圆角",
    distance: "距离",
    barBorderRadius: "柱条圆角",
    barMaxWidth: "柱条最大宽度",
    barGap: "组内柱条间距",
    barCategoryGap: "组间间距",
    showBackground: "柱条背景",
    borderType: "边框类型",
    mode: "模式",
    radial: "径向渐变",
    backgroundStyle: "背景样式",
    onZero: "轴在零刻度",
    alignWithLabel: "对齐标签",
    colorStops: "起止颜色",
    min: "最小值",
    max: "最大值",
    minSize: "最小值映射宽度",
    maxSize: "最大值映射宽度",
    gap: "间距",
    orient: "方向",
    sort: "排序",
    funnelAlign: "漏斗对齐",
    splitNumber: "分割段数",
    shape: "形状",
    center: "中心",
    radius: "半径",
    symbolRotate: "标志旋转角度",
    startAngle: "起始角度",
    areaStyle: "区域样式",
    splitArea: "区域分隔",
    opacity: "不透明度",
    mapObj: "JSON地图文件",
    textGap: "文本间距",
    itemWidth: "宽度",
    itemHeight: "高度",
    calculable: "拖拽手柄",
    aspectScale: "长宽比",
    roam: "缩放",
    zoom: "缩放比例",
    areaColor: "区域颜色",
    inRange: "颜色范围",
    itemStyle: "样式",
    method: "方法",
    formulaOn: "公式位置",
    smooth: "平滑",
    clockwise: "顺时针",
    formatter: "格式",
  },
};
