const textStyle = {
  color: "#333",
  fontStyle: "normal",
  fontWeight: "bold",
  fontFamily: "Microsoft YaHei",
  fontSize: 20,
  lineHeight: 5,
  textBorderColor: "transparent",
  textBorderWidth: 0,
  textShadowColor: "transparent",
  textShadowBlur: 2,
  textShadowOffsetX: 1,
  textShadowOffsetY: 1,
};
const itemStyle = {
  borderColor: "#000",
  borderWidth: 0,
  borderType: "solid",
  shadowBlur: 0,
  shadowColor: "rgba(0, 0, 0, 0)",
  shadowOffsetX: 0,
  shadowOffsetY: 0,
};
const lineStyle = {
  show: true,
  color: "#DAE1FA",
  width: 2,
  type: "solid",
  shadowBlur: 0,
  shadowColor: "rgba(0, 0, 0, 0.5)",
  shadowOffsetX: 0,
  shadowOffsetY: 0,
};
const label = {
  show: false,
  //formatter: '{@[0]},{@[1]}',
  position: "top",
  distance: 5,
  rotate: 0,
  offset: [0, 0],
  color: "inherit",
  fontWeight: "normal",
  fontFamily: "san-serif",
  fontSize: 12,
  align: "center",
  verticalAlign: "middle",
  backgroundColor: "transparent",
  borderColor: "inherit",
  borderWidth: 0,
  borderRaduis: 0,
  padding: [0, 0, 0, 0],
};
const title = {
  show: true,
  text: "",
  link: "",
  target: "blank",
  textStyle: textStyle,
  subtext: "",
  sublink: "",
  subtarget: "blank",
  subtextStyle: {
    color: "#aaa",
    fontStyle: "normal",
    fontWeight: "bold",
    fontFamily: "Arial",
    fontSize: 14,
    align: "center",
    verticalAlign: "middle",
    lineHeight: 5,
    textBorderColor: "transparent",
    textBorderWidth: 0,
    textShadowColor: "transparent",
    textShadowBlur: 2,
    textShadowOffsetX: 1,
    textShadowOffsetY: 1,
  },
  textAlign: "auto",
  textVerticalAlign: "auto",
  padding: [0, 0, 0, 0],
  itemGap: 10,
  left: "center",
  right: "auto",
  top: "5%",
  bottom: "auto",
  backgroundColor: "transparent",
  borderColor: "#ccc",
  borderWidth: 0,
  borderRaduis: 0,
};
const xAxis = {
  show: true,
  type: "category",
  position: "bottom",
  name: "",
  nameLocation: "center",
  nameTextStyle: {
    color: "#333",
    fontStyle: "normal",
    fontWeight: "normal",
    fontFamily: "Microsoft YaHei",
    fontSize: 14,
    lineHeight: 5,
  },
  nameGap: 25,
  nameRotate: 0,
  inverse: false,
  axisLine: {
    show: true,
    onZero: true,
    symbol: ["none", "none"],
    symbolSize: [6, 9],
    symbolOffset: 6,
    lineStyle: {
      color: "#333",
      width: 1,
      type: "solid",
    },
  },
  axisTick: {
    show: true,
    alignWithLable: false,
    interval: "auto",
    inside: false,
    length: 5,
    lineStyle: {
      color: "#333",
      width: 1,
      type: "solid",
    },
  },
  axisLabel: {
    show: true,
    color: "#333",
    interval: "auto",
    rotate: 0,
    fontWeight: "normal",
    fontFamily: "Microsoft YaHei",
    fontSize: 14,
    lineHeight: 5,
  },
  splitLine: {
    show: false,
    interval: "auto",
    lineStyle: {
      color: "rgba(28, 51, 28, 0.81)",
      width: 1,
      type: "dashed",
    },
  },
};
const yAxis = {
  show: true,
  type: "value",
  position: "left",
  name: "",
  nameLocation: "end",
  nameTextStyle: {
    color: "#333",
    fontStyle: "normal",
    fontWeight: "normal",
    fontFamily: "Microsoft YaHei",
    fontSize: 14,
    lineHeight: 5,
  },
  nameGap: 25,
  nameRotate: 0,
  inverse: false,
  axisLine: {
    show: true,
    onZero: true,
    symbol: ["none", "arrow"],
    symbolOffset: 6,
    symbolSize: [6, 9],
    lineStyle: {
      color: "#333",
      width: 1,
      type: "solid",
    },
  },
  axisTick: {
    show: true,
    alignWithLable: false,
    interval: "auto",
    inside: false,
    length: 3,
    lineStyle: {
      color: "#333",
      width: 1,
      type: "solid",
    },
  },
  axisLabel: {
    show: true,
    formatter: "{value}",
    color: "#333",
    interval: "auto",
    rotate: 0,
    fontWeight: "normal",
    fontFamily: "Microsoft YaHei",
    fontSize: 14,
    lineHeight: 5,
  },
  splitLine: {
    show: true,
    interval: "auto",
    lineStyle: {
      color: "rgba(28, 51, 28, 0.81)",
      width: 1,
      type: "dotted",
    },
  },
};
const legend = {
  show: true,
  type: "plain",
  left: "center",
  right: "auto",
  top: "5%",
  bottom: "auto",
  orient: "horizontal",
  align: "auto",
  padding: 0,
  itemGap: 10,
  itemWidth: 25,
  itemHeight: 14,
  textStyle: {
    color: "#333",
    fontWeight: "normal",
    fontFamily: "sans-serif",
    fontSize: 14,
    lineHeight: 56,
  },
};
const backgroundPalette = {
  mode: "pureColor",
  pureColor: "transparent",
  linear: {
    type: "linear",
    x: 0,
    y: 0,
    x2: 0,
    y2: 1,
    colorStops: [
      {
        offset: 0,
        color: "red", // 0% 处的颜色
      },
      {
        offset: 1,
        color: "blue", // 100% 处的颜色
      },
    ],
    global: false, // 缺省为 false
  },
  radial: {
    type: "radial",
    x: 0.5,
    y: 0.5,
    r: 0.5,
    colorStops: [
      {
        offset: 0,
        color: "red", // 0% 处的颜色
      },
      {
        offset: 1,
        color: "blue", // 100% 处的颜色
      },
    ],
    global: false, // 缺省为 false
  },
};
const palette = {
  mode: "pureColor",
  pureColor: [
    "#c23531",
    "#2f4554",
    "#61a0a8",
    "#d48265",
    "#91c7ae",
    "#749f83",
    "#ca8622",
    "#bda29a",
    "#6e7074",
    "#546570",
    "#c4ccd3",
    "rgba(0,0,84,1)",
  ],
  linear: [
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "#2c3e50" },
        { offset: 1, color: "#bdc3c7" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "#ee9ca7" },
        { offset: 1, color: "#ffdde1" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
    {
      type: "linear",
      x: 0,
      y: 0,
      x2: 0,
      y2: 1,
      colorStops: [
        { offset: 0, color: "red" },
        { offset: 1, color: "blue" },
      ],
      global: false,
    },
  ],
};
const grid = {
  containLabel: true,
  show: true,
  backgroundColor: "transparent",
  left: "5%",
  right: "5%",
  top: "20%",
  bottom: "10%",
};
const visualMapC = {
  show: true,
  type: "continuous",
  orient: "vertical",
  left: "1%",
  right: "auto",
  bottom: "1%",
  top: "auto",
  min: 1,
  max: 10,
  text: ["High", "Low"],
  textGap: 10,
  itemWidth: 20,
  itemHeight: 140,
  calculable: true,
  inRange: {
    color: ["#D7DA8B", "#E15457"],
  },
};
const visualMapP = {
  show: true,
  type: "piecewise",
  pieces: [
    { min: 0, max: 1, color: "red" }, // 不指定 max，表示 max 为无限大（Infinity）。
    { min: 2, max: 3, color: "blue" },
    { min: 4, max: 5, color: "grey" },
    { min: 6, max: 7, color: "pink" },
    { min: 8, max: 9, color: "yellow" },
  ],
  selectedMode: "multiple",
  orient: "vertical",
  left: "1%",
  right: "auto",
  bottom: "1%",
  top: "auto",
  itemGap: 10,
  itemWidth: 20,
  itemHeight: 14,
  itemSymbol: "roundRect",
};

const TIMELINELABEL = {
  position: "auto",
  show: true,
  interval: "auto",
  rotate: 0,
  color: "#A4B1D7",
  fontWeight: 100,
  fontFamily: "san-serif",
  fontSize: 12,
  align: "auto",
  verticalAlign: "auto",
  lineHeight: 5,
  backgroundColor: "transparent",
  borderColor: "inherit",
  borderWidth: 0,
  borderRaduis: 0,
  padding: [0, 0, 0, 0],
  shadowBlur: 0,
  shadowColor: "rgba(0, 0, 0, 0)",
  shadowOffsetX: 1,
  shadowOffsetY: 1,
  textBorderColor: "transparent",
  textBorderWidth: 0,
  textShadowColor: "transparent",
  textShadowBlur: 0,
  textShadowOffsetX: 0,
  textShadowOffsetY: 0,
};
const CHECKPOINTSTYLE = {
  symbol: "circle",
  symbolSize: 15,
  color: "#316bf3",
  borderColor: "#fff",
  borderWidth: 2,
  shadowBlur: 2,
  shadowOffsetX: 1,
  shadowOffsetY: 1,
  shadowColor: "rgba(0, 0, 0, 0.3)",
  animation: true,
  animationDuration: 300,
  animationEasing: "quinticInOut",
};
const CONTROLSTYLE = {
  show: true,
  showPlayBtn: true,
  showPrevBtn: true,
  showNextBtn: true,
  itemSize: 24,
  itemGap: 12,
  position: "left",
  color: "#A4B1D7",
  borderColor: "#A4B1D7",
  borderWidth: 1,
  borderType: "solid",
  shadowBlur: 0,
  shadowColor: "rgba(0, 0, 0, 0)",
  shadowOffsetX: 0,
  shadowOffsetY: 0,
  prevBtnSize: 18,
  nextBtnSize: 18,
};
const timeline = {
  show: true,
  axisType: "category",
  orient: "horizontal",
  inverse: false,
  left: "10%",
  right: "10%",
  top: "85%",
  bottom: "1%",
  height: 40,
  padding: 5,
  currentIndex: 0,
  autoPlay: true,
  rewind: false,
  loop: true,
  playInterval: 2000,
  realtime: true,
  controlPosition: "left",
  symbol: "emptyCircle",
  symbolSize: 10,
  symbolRotate: 0,
  symbolOffset: [0, 0],
  backgroundColor: "rgba(0,0,0,0)",
  borderColor: "#ccc",
  borderWidth: 0,
  lineStyle: lineStyle,
  itemStyle: {
    emphasis: {},
    color: "#A4B1D7",
    borderWidth: 1,
  },
  label: TIMELINELABEL,
  checkpointStyle: CHECKPOINTSTYLE,
  controlStyle: CONTROLSTYLE,
  /* emphasis: {
    label: TIMELINELABEL,
    itemStyle: {
      ...itemStyle,
      //color: "#A4B1D7",
    },
    checkpointStyle: CHECKPOINTSTYLE,
    controlStyle: CONTROLSTYLE,
  }, */
};
const dataZoom = {
  handleSize: "100%",
  handleIcon:
    "path://M306.1,413c0,2.2-1.8,4-4,4h-59.8c-2.2,0-4-1.8-4-4V200.8c0-2.2,1.8-4,4-4h59.8c2.2,0,4,1.8,4,4V413z",
  left: "5%",
  right: "5%",
  top: "92%",
  bottom: "5%",
  height: 20,
  borderColor: "#ddd",
};

export {
  textStyle,
  itemStyle,
  lineStyle,
  label,
  title,
  xAxis,
  yAxis,
  legend,
  grid,
  visualMapC,
  visualMapP,
  timeline,
  dataZoom,
  palette,
  backgroundPalette,
};
