import {
  textStyle,
  itemStyle,
  lineStyle,
  label,
  title,
  xAxis,
  yAxis,
  legend,
  grid,
  visualMapC,
  visualMapP,
  timeline,
  dataZoom,
  palette,
  backgroundPalette,
} from "../element";
import editor from "../editor";

const atom = {
  i: "0",
  x: 1,
  y: 2,
  w: 8,
  h: 7,
  stacic:false,
super:false,
  atomType: "echart",
  atomBorder: { width: 0, type: "solid", color: "#808080", radius: 1 },
  atomAnimation: { order: 1, enter: "fadeIn", leave: "fadeOut" },
  atomContent: {
    atomName: "simple-sankey",
    detail: {
      sheetData: [
        ["来源", "流向", "数量"],
        ["基线", "吸烟", 120],
        ["基线", "不吸烟", 120],
        ["吸烟", "失访", 20],
        ["不吸烟", "失访", 20],
        ["吸烟", "肺癌", 80],
        ["不吸烟", "肺癌", 20],
        ["吸烟", "不得肺癌", 20],
        ["不吸烟", "不得肺癌", 80],
      ],
      jsonData: [
        ["来源", "流向", "数量"],
        ["基线", "吸烟", 120],
        ["基线", "不吸烟", 120],
        ["吸烟", "失访", 20],
        ["不吸烟", "失访", 20],
        ["吸烟", "肺癌", 80],
        ["不吸烟", "肺癌", 20],
        ["吸烟", "不得肺癌", 20],
        ["不吸烟", "不得肺癌", 80],
      ],
      nr: 8,
      nc: 2,
      simpleSankey: {
        left: "5%",
        right: "5%",
        top: "10%",
        bottom: "5%",
        nodeWidth: 20,
        nodeGap: 8,
        orient: "horizontal",
        label: {
          show: true,
          position: "right",
          distance: 5,
          color: "#333",
          fontWeight: "normal",
          fontFamily: "Microsoft YaHei",
          fontSize: 12,
        },
      },
      animation: true,
      palette,
      backgroundPalette,
      title,
      legend,
      label: {
        ...label,
        show: true,
        position: "outside",
        formatter: "{@[0]}: {@[1]} {d}%",
      },
      itemStyle,
      emphasis: {
        label,
        itemStyle,
      },
    },
  },
};
export { atom, editor };
