export default {
  specialLabels: {},
  selectOptions: {
    enter: [
      { label: "弹跳", value: "bounce" },
      { label: "闪光", value: "flash" },
      { label: "脉冲", value: "pulse" },
      { label: "橡皮筋", value: "rubberBand" },
      { label: "抖动", value: "shake" },
      { label: "摇摆", value: "swing" },
      { label: "tada", value: "tada" },
      { label: "摇晃", value: "wobble" },
      { label: "jello", value: "jello" },
      { label: "心跳", value: "heartBeat" },
      { label: "弹跳进入", value: "bounceIn" },
      { label: "左侧弹跳", value: "bounceInLeft" },
      { label: "右侧弹跳", value: "bounceInRight" },
      { label: "上方弹跳", value: "bounceInUp" },
      { label: "下方弹跳", value: "bounceInDown" },
      { label: "淡入", value: "fadeIn" },
      { label: "左侧淡入", value: "fadeInLeft" },
      { label: "右侧淡入", value: "fadeInRight" },
      { label: "上方淡入", value: "fadeInDown" },
      { label: "下方淡入", value: "fadeInUp" },
      { label: "翻转", value: "flip" },
      { label: "翻转-X", value: "flipInX" },
      { label: "翻转-Y", value: "flipInY" },
      { label: "光速", value: "lightSpeedIn" },
      { label: "旋转", value: "rotateIn" },
      { label: "左侧旋转", value: "rotateInDownLeft" },
      { label: "右侧旋转", value: "rotateInDownRight" },
      { label: "上方旋转", value: "rotateInUpLeft" },
      { label: "下方旋转", value: "rotateInDownRight" },
      { label: "左侧浮入", value: "slideInLeft" },
      { label: "右侧浮入", value: "slideInRight" },
      { label: "下方浮入", value: "slideInUp" },
      { label: "上方浮入", value: "slideInDown" },
      { label: "缩放", value: "zoomIn" },
      { label: "左-缩放", value: "zoomInLeft" },
      { label: "右-缩放", value: "zoomInRight" },
      { label: "上-缩放", value: "zoomInDown" },
      { label: "下-缩放", value: "zoomInUp" },
      { label: "转入", value: "rollIn" },
    ],
    leave: [
      { label: "弹出", value: "bounceOut" },
      { label: "弹出-左", value: "bounceOutLeft" },
      { label: "弹出-右", value: "bounceOutRight" },
      { label: "弹出-上", value: "bounceOutUp" },
      { label: "弹出-下", value: "bounceOutDown" },
      { label: "淡出", value: "fadeOut" },
      { label: "淡出-左", value: "fadeOutLeft" },
      { label: "淡出-右", value: "fadeOutRight" },
      { label: "淡出-上", value: "fadeOutUp" },
      { label: "淡出-下", value: "fadeOutDown" },
      { label: "翻转-X", value: "flipOutX" },
      { label: "翻转-Y", value: "flipOutY" },
      { label: "光速", value: "lightSpeedOut" },
      { label: "旋转", value: "rotateOut" },
      { label: "旋转-左下", value: "rotateOutDownLeft" },
      { label: "旋转-右下", value: "rotateOutDownRight" },
      { label: "旋转-左上", value: "rotateOutUpLeft" },
      { label: "旋转-右上", value: "rotateOutUpRight" },
      { label: "左侧浮出", value: "slideOutLeft" },
      { label: "右侧浮出", value: "slideOutRight" },
      { label: "上方浮出", value: "slideOutUp" },
      { label: "下方浮出", value: "slideOutDown" },
      { label: "缩放", value: "zoomOut" },
      { label: "缩放-左", value: "zoomOutLeft" },
      { label: "缩放-右", value: "zoomOutRight" },
      { label: "缩放-上", value: "zoomOutUp" },
      { label: "缩放-下", value: "zoomOutDown" },
      { label: "掉落", value: "hinge" },
      { label: "转出", value: "rollOut" },
    ],
  },
  labels: {
    enter: "进入动画",
    leave: "离开动画",
    order: "出场次序",
  },
};
